import React, { useState } from "react";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const FourAndSix = () => {
  const ratio = 18.18;
  const [gramsOfGroundCoffee, setGramsOfGroundCoffee] = useState(11);
  const [gramsOfWater, setGramsOfWater] = useState(200);

  function setGramsOfWaterValue(event: React.FormEvent<HTMLInputElement>) {
    const { value } = event.currentTarget;
    setGramsOfWater(Number(value));
    setGramsOfGroundCoffee(Number((Number(value) / ratio).toFixed(2)));
  }
  function setGramsOfCoffeValue(event: React.FormEvent<HTMLInputElement>) {
    const { value } = event.currentTarget;
    setGramsOfGroundCoffee(Number(value));
    setGramsOfWater(Math.ceil(Number(value) * ratio));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Weird Coffee Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button>
          <Link passHref href="/">
            <Image
              alt="home button"
              src="/home-button.svg"
              height="30"
              width="30"
            />
          </Link>
        </button>
        <h1>James Hoffmann Method</h1>
        <label htmlFor="ground coffee">Grams of Ground Coffee: </label>
        <input
          type="number"
          min="0"
          name="ground coffee"
          step="1"
          value={gramsOfGroundCoffee}
          onChange={setGramsOfCoffeValue}
        />
        <br />
        <label htmlFor="water">Grams of Water: </label>
        <input
          type="number"
          min="0"
          name="water"
          step="1"
          value={gramsOfWater}
          onChange={setGramsOfWaterValue}
        />
        <br />
        <h2>Measurements</h2>
        <p>
          You will use {gramsOfGroundCoffee} grams of coffee with {gramsOfWater}{" "}
          grams of water.{" "}
        </p>
        <h2>Grind</h2>
        <p>
          {" "}
          Finer end of medium, assuming this is light roasted coffee. The darker
          you go the more you may prefer to increase the dose and coarsen the
          grind.
        </p>
        <h2>
          Recipe -{" "}
          <Link href="https://www.youtube.com/watch?v=j6VlT_jUVPc">
            Video Reference
          </Link>
        </h2>
        <ol>
          <li>
            Put the filter into the cap. Don't rinse or preheat the brewer (it
            doesn't make any difference)
          </li>
          <li>Put coffee into the brewer</li>
          <li>
            Place on scales and then add water, aiming to wet all the coffee
            during pouring
          </li>
          <li>
            Start a timer, and immediately place the piston piece into the top
            of the brewer, about 1cm in
          </li>
          <li>Wait 2 minutes</li>
          <li>Holding the brewer and the piston, gently swirl the brewer</li>
          <li>Wait 30 seconds</li>
          <li>Press gently all the way</li>
          <li>Drink</li>
        </ol>
      </main>
    </div>
  );
};

export default FourAndSix;
