import type { NextPage } from "next";
import Link from "next/link";
import React, { useState } from "react";

import styles from "../styles/Home.module.css";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weird Coffee Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Methods:</h1>
        <ul className={styles.brewers}>
          <li>
            <Link href="/v60/four-and-six">V60 - 4:6</Link>
          </li>
          <li>Fellow Dripper - Coming Soon</li>
          <li>
            {" "}
            <Link href="/aeropress/hoffmann-method">
              AeroPress - Hoffmann Method
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
