import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [gramsOfGroundCoffee, setGramsOfGroundCoffee] = useState(0);
  const [gramsOfWater, setGramsOfWater] = useState(0);

  function setGramsOfWaterValue(event: React.FormEvent<HTMLInputElement>) {
    const { value } = event.currentTarget;
    setGramsOfWater(Number(value));
    setGramsOfGroundCoffee(Number((Number(value) / 15).toFixed(2)));
  }
  function setGramsOfCoffeValue(event: React.FormEvent<HTMLInputElement>) {
    const { value } = event.currentTarget;
    setGramsOfGroundCoffee(Number(value));
    setGramsOfWater(Number(value) * 15);
  }

  const firstFourty = gramsOfWater * 0.4;
  const secondSixty = gramsOfWater * 0.6;

  return (
    <div className={styles.container}>
      <Head>
        <title>Weird Coffee Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>4:6 Method</h1>
        <label htmlFor="ground coffee">Grams of Ground Coffee: </label>
        <input
          type="number"
          min="0"
          name="ground coffee"
          step="1"
          value={gramsOfGroundCoffee}
          onChange={setGramsOfCoffeValue}
        />
        <br />
        <label htmlFor="water">Grams of Water: </label>
        <input
          type="number"
          min="0"
          name="water"
          step="1"
          value={gramsOfWater}
          onChange={setGramsOfWaterValue}
        />
        <br />
        <h2>Measurements</h2>
        <p>
          You will use {gramsOfGroundCoffee} grams of coffee with {gramsOfWater}{" "}
          grams of water{" "}
        </p>
        <p>
          You will use {gramsOfWater * 0.4} grams of water for your first 2
          pours and {gramsOfWater * 0.6} grams of water for the remaining pours
        </p>
        <h2>Pours</h2>
        <h3>First 40% - {firstFourty}g</h3>
        <p>
          For a <strong>balanced</strong> cup, perform two{" "}
          {(gramsOfWater * 0.4) / 2} gram pours
        </p>
        <p>
          For a <strong>sweeter</strong> cup, the first pour will be about{" "}
          {Math.round(firstFourty * 0.4)} grams and the second pour will be
          about {Math.round(firstFourty * 0.6)}. Remember that you just want a
          smaller first pour and a bigger second pour here.
        </p>
        <p>
          For a <strong>brighter</strong> cup, the first pour will be about{" "}
          {Math.round(firstFourty * 0.6)} grams and the second pour will be{" "}
          {Math.round(firstFourty * 0.4)}. Remember that you just want a bigger
          first pour and a smaller second pour here.
        </p>
        <h3>Remaing 60% - {secondSixty}g</h3>
        <p>
          For a <strong>light</strong> cup of coffee, perform one pour of{" "}
          {secondSixty} grams
        </p>
        <p>
          For a <strong>stronger</strong> cup of coffee, perform two pours of{" "}
          {secondSixty / 2} grams each
        </p>
        <p>
          For a <strong>even stronger</strong> cup of coffee, perform three
          pours of {secondSixty / 3} grams each
        </p>
      </main>
    </div>
  );
};

export default Home;
